input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/opensubtitles/opensubtitles_train.src.txt
    target_files:
      - ../data/opensubtitles/opensubtitles_train.target.txt

input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/opensubtitles/opensubtitles_valid.0.src.txt
    target_files:
      - ../data/opensubtitles/opensubtitles_valid.0.target.txt
