input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/opensubtitles/opensubtitles_parallel_src.txt
    target_files:
      - ../data/opensubtitles/opensubtitles_parallel_target.txt

input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/opensubtitles/opensubtitles_parallel_src.txt
    target_files:
      - ../data/opensubtitles/opensubtitles_parallel_target.txt
