input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/opensubtitles/opensubtitles_2016_train_src.txt
    target_files:
      - ../data/opensubtitles/opensubtitles_2016_train_target.txt

input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/opensubtitles/opensubtitles_2016_valid_src.txt
    target_files:
      - ../data/opensubtitles/opensubtitles_2016_valid_target.txt
