input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/reddit_movies/reddit_corpus_movies_train_src.txt
    target_files:
      - ../data/reddit_movies/reddit_corpus_movies_train_tar.txt

input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/reddit_movies/reddit_corpus_movies_valid_src.txt
    target_files:
      - ../data/reddit_movies/reddit_corpus_movies_valid_tar.txt
