input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/wmt16/train.tok.clean.bpe.32000.en
    target_files:
      - ../data/wmt16/train.tok.clean.bpe.32000.de

input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - ../data/wmt16/newtest2016.tok.bpe.32000.en
    target_files:
      - ../data/wmt16/newtest2016.tok.bpe.32000.de
