batch_size: 64
eval_every_n_steps: 25000
buckets: 10,20,30,40
hooks:
  - class: PrintModelAnalysisHook
  - class: MetadataCaptureHook
  - class: TrainSampleHook
    params:
      every_n_steps: 1000
  - class: TokensPerSecondCounter
    params:
       every_n_steps: 100
