batch_size: 128
train_steps: 100000
eval_every_n_steps: 10000
buckets: 10,20,30,40
hooks:
  - class: PrintModelAnalysisHook
  - class: MetadataCaptureHook
  - class: TrainSampleHook
    params:
      every_n_steps: 1000
  - class: TokensPerSecondCounter
    params:
       every_n_steps: 100
